# Generated by Django 4.1.2 on 2022-10-16 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_question_questionoptions_questionset_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterField(
            model_name='question',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.questionset'),
        ),
        migrations.AlterField(
            model_name='questionoptions',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.question'),
        ),
    ]
